version: '3.8'
services:
  mongodb:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB} 